### ISSUE TITLE
extension error

### ISSUE THREAD

**Issue by syra-project** [veryphatic/directus-webcam-capture-interface#1]
directus version 10.10.4

![Gambar WhatsApp 2024-03-22 pukul 15 58 30_0bf5c2e8](https://github.com/veryphatic/directus-webcam-capture-interface/assets/107026278/02aa79f0-b401-494c-8a1e-ba5551167167)
![Gambar WhatsApp 2024-03-22 pukul 15 56 25_dd30e9e9](https://github.com/veryphatic/directus-webcam-capture-interface/assets/107026278/babbb1d0-1a9e-417e-99b7-f14664dde58f)

**Comment by veryphatic** [comment]
Hi, can you show me the browser's console output; also the version of the extension?

**Comment by veryphatic** [comment]
Closing due to no further details regarding bug

**Comment by Dominic-Preap** [comment]
@veryphatic Hi, I'm installing your extension from marketplace and got blank on New Fileds drawer. My Directus version is 10.13.2.

![image](https://github.com/user-attachments/assets/7037bc61-b69c-4022-81de-67da1ee807f1)

![image](https://github.com/user-attachments/assets/3dd96b9b-c385-4e68-a2bc-6927dbb82fe0)

**Comment by Dominic-Preap** [comment]
It appears svg bundle is not working well. I comment this line and try to build local and it's working. 

![image](https://github.com/user-attachments/assets/0dd02c9d-c771-4978-a1e2-463708e11ada)

**Comment by veryphatic** [comment]
Thanks for the detail. I'll take a look
